services:
  app:
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    volumes:
      - ./:/app   # 코드 변경 시 바로 반영
    restart: unless-stopped

  db:
    ports:
      - "3307:3306"   # 개발용은 3307
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data