version: "3.9"

services:
  app:
    image: uzemm/book-cycle:latest
    container_name: book-cycle-app
    depends_on:
      - db
      - redis
    networks:
      - bookcycle-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  db:
    image: mysql:8.0
    container_name: book-cycle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookcycle
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: 1234
    networks:
      - bookcycle-network

  redis:
    image: redis:7
    container_name: book-cycle-redis
    networks:
      - bookcycle-network

networks:
  bookcycle-network:
    driver: bridge