spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
