spring.datasource.url=jdbc:mysql://localhost:3306/book_cycle?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1

custom.jwt.secret=bXktc2VjcmV0LWtleS1zaG91bGQtYmUtbG9uZy1lbm91Z2gtMzJieXRlcw==
